In [6]:
import pandas as pd
import requests as req

In [7]:
df = pd.read_excel('/home/triviiz/Documents/Cours/US01/2019-US01-Data-Science-master/Data-sheet-STUDENTS.xlsx', header = 2, index_col = 0)
isoCodes = {}

In [8]:
def getIsocodes (df) :
    thingsGotten = 0

    for index, name in df["Country (according to CN Gov):"].items() :
        #print("Trying " + name)
        if name in isoCodes :
            #print (name + " already in Table > Continue")
            continue

        thingsGotten += 1

        requestedName = name
        if " (not bri)" in requestedName.lower() :
            requestedName = requestedName[:-10]
            #print("New name = " + name)

        if requestedName == "Thailiand" :
            requestedName = "Thailand"

        if requestedName == "The United Arab Emirates" :
            requestedName = "United Arab Emirates"

        r = req.get("https://restcountries.eu/rest/v2/name/" + requestedName, auth = ('user', 'pass'))
        if r.status_code == 200 :
            alpha3 = r.json()[0]["alpha3Code"]
            print(name + " -> " + alpha3)
            isoCodes[name] = alpha3
        else :
            print (name + " -> Error " + str(r.status_code) + " : " + r.json()["message"])

    if thingsGotten == 0 :
        print("Table already complete")
    else :
        print(str(thingsGotten) + " things added to table")

In [9]:
getIsocodes(df)
df["isocode"] = df["Country (according to CN Gov):"].apply(lambda x : isoCodes[x])

Afghanistan -> AFG
Albania -> ALB
Armenia -> ARM
Azerbaijan -> AZE
Bahrain -> BHR
Bangladesh -> BGD
Belarus -> BLR
Bhutan -> BTN
Bosnia and Herzegovina -> BIH
Brunei -> BRN
Bulgaria -> BGR
Cambodia -> KHM
China -> CHN
Croatia -> HRV
Czech Republic -> CZE
East Timor -> TLS
Egypt -> EGY
Estonia -> EST
France (Not BRI) -> FRA
Georgia -> GEO
Germany (not BRI) -> DEU
Hungary -> HUN
India -> IOT
Indonesia -> IDN
Iran -> IRN
Iraq -> IRQ
Israel -> ISR
Jordan -> JOR
Kazakhstan -> KAZ
Kuwait -> KWT
Kyrgyzstan -> KGZ
Laos -> LAO
Latvia -> LVA
Lebanon -> LBN
Lithuania -> LTU
Macedonia -> MKD
Malaysia -> MYS
Maldives -> MDV
Moldova -> MDA
Mongolia -> MNG
Montenegro -> MNE
Myanmar -> MMR
Nepal -> NPL
Oman -> OMN
Pakistan -> PAK
Philippines -> PHL
Poland -> POL
Qatar -> QAT
Romania -> ROU
Russia -> RUS
Saudi Arabia -> SAU
Serbia -> SRB
Singapore -> SGP
Slovakia -> SVK
Slovenia -> SVN
Sri Lanka -> LKA
Syria -> SYR
Tajikistan -> TJK
Thailiand -> THA
The United Arab Emirates -> ARE
Turkey -> TUR
Turkmenistan -> TKM
United Kingdom (Not BRI) -> GBR
United States of America (Not BRI) -> USA
Ukraine -> UKR
Uzbekistan -> UZB
Vietnam -> VNM
Yemen -> YEM
68 things added to table

In [11]:
def getIndicator (df, indicator, url) :
    
    thingsGotten = 0
    indicators = {}

    for index, (name, isocode) in df[["Country (according to CN Gov):", "isocode"]].items() :
        #print("Trying " + name)
        if name in indicators :
            #print (name + " already in Table > Continue")
            continue

        thingsGotten += 1

        url = "http://api.worldbank.org/v2/country/" + isocode + "/indicator/" + indicator
        
        r = req.get(url, auth = ('user', 'pass'))
        if r.status_code == 200 :
            for query in r.json()[1] :
                if query["value"] != null :
                    lastData = [query["date"], query["value"]]
            print(name + " -> " + indicator[1] + "(" + indicator[0] + ")")
            indicators[name] = lastData
        else :
            print (name + " -> Error " + str(r.status_code) + " : " + r.json()["message"])
        break

    if thingsGotten == 0 :
        print("Table already complete")
    else :
        print(str(thingsGotten) + " things added to table")

In [12]:
df.to_pickle("pickledDF.pickle")

In [14]:
df = pd.read_pickle("/home/triviiz/Downloads/savedDF.pickle")  #Continue with Thomas' dataframe

In [16]:
df

,Country (according to CN Gov):,Date of research inquiry,HF Index of Economic Freedom (Scale: 1-100),Heritage Foundation Index of Economic Freedom (Global Ranking),Bertelsmann Transformation index (BTI),Bertelsmann Transformation index (BTI) - Ranking,IMF WB\nCustoms and other import duties (% of tax revenue) 2016,WB IMF Non-performing loans to total gross loans ratio (%),Moody's Socvereign Ratings List,S&P Sovereign Ratings List,...,WB Cost of Starting a Business,WB Ease of Doing Business Index (1 = most business-friendly regulations),WB Logistics Performance Index (LPI) (range: 1-5),IFDI Net Inflows (% of GDP),ED National Electric Power Consumption TwH,"WHO Current Health Expenditure p.c., PPP USD",WB Research Expenditure % of GDP,WIPO Trademark applications,WIPO Patent Applications,isocode
1,Afghanistan,NaT,NaN,NaN,NaN,NaN,35.2031,12.2018,NaN,NaN,...,NaN,NaN,NaN,0.718898,NaN,162.781,NA,NA,NA,AFG
2,Albania,NaT,NaN,NaN,NaN,NaN,2.21646,13.2325,NaN,NaN,...,NaN,NaN,NaN,8.01551,NaN,759.667,0.15412,1232,14,ALB
3,Armenia,NaT,NaN,NaN,NaN,NaN,6.27539,5.43232,NaN,NaN,...,NaN,NaN,NaN,2.04411,NaN,876.857,0.2277,2685,107,ARM
4,Azerbaijan,NaT,NaN,NaN,NaN,NaN,7.57185,NA,NaN,NaN,...,NaN,NaN,NaN,2.98895,NaN,1193.06,0.18521,2817,144,AZE
5,Bahrain,NaT,NaN,NaN,NaN,NaN,27.3861,NA,NaN,NaN,...,NaN,NaN,NaN,4.01407,NaN,1866.3,0.10116,253,8,BHR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,United States of America (Not BRI),NaT,NaN,NaN,NaN,NaN,2.64259,1.12682,NaN,NaN,...,NaN,NaN,NaN,1.2608,NaN,9869.74,2.74418,428225,293904,USA
65,Ukraine,NaT,NaN,NaN,NaN,NaN,3.99768,54.5413,NaN,NaN,...,NaN,NaN,NaN,1.8925,NaN,534.191,0.44853,47531,2283,UKR
66,Uzbekistan,NaT,NaN,NaN,NaN,NaN,5.18686,0.436415,NaN,NaN,...,NaN,NaN,NaN,1.23623,NaN,416.904,0.18903,6750,357,UZB
67,Vietnam,NaT,NaN,NaN,NaN,NaN,NA,1.82498,NaN,NaN,...,NaN,NaN,NaN,6.32786,NaN,356.28,0.44113,55313,592,VNM
68,Yemen,NaT,NaN,NaN,NaN,NaN,NA,NA,NaN,NaN,...,NaN,NaN,NaN,-1.04813,NaN,144.518,NA,2941,15,YEM